if ("hello") console.log("String is always true");
if ("") console.log("Empty String is always false");
if (0) console.log("Number 0 is always false");
if (null) console.log("Null is always false");
if (undefined) console.log("Undefined is always false");
if (NaN) console.log("NaN is always false");
if (true) console.log("True is always true");
if (false) console.log("False is always false");
if (1) console.log("Number 1 is always true");
if (-1) console.log("Number -1 is always true");
if (0n) console.log("BigInt 0n is always false");
if (1n) console.log("BigInt 1n is always true");
if (Symbol("hello")) console.log("Symbol is always true");
if ([]) console.log("Array is always true");
if ({}) console.log("Object is always true");
if (function () { }) console.log("Function is always true");
if (new Date()) console.log("Date is always true");
if (new Error()) console.log("Error is always true");
if (new Map()) console.log("Map is always true");
if (new Set()) console.log("Set is always true");
if (new WeakMap()) console.log("WeakMap is always true");
if (new WeakSet()) console.log("WeakSet is always true");
if (new Promise(() => { })) console.log("Promise is always true");
if (new Proxy({}, {})) console.log("Proxy is always true");
